export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const FETCH_WEATHER_PENDING = "FETCH_WEATHER_PENDING";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILED = "FETCH_WEATHER_FAILED";

export const REVERSE_GEOCODE_PENDING = "REVERSE_GEOCODE_PENDING";
export const REVERSE_GEOCODE_SUCCESS = "REVERSE_GEOCODE_SUCCESS";
export const REVERSE_GEOCODE_FAILED = "REVERSE_GEOCODE_FAILED";

